### PR TITLE
Ci verbose

### PR DESCRIPTION
**Pull request by rtau**

### CODE REVIEW

**Comment by rtau** [comment]
Waiting for pipeline complete before marking it ready for review.

**Comment by rtau** [comment]
Just triggerred a sucessful run at https://github.com/rtau/hk-bus-crawling/actions/runs/7212537579, which https://github.com/rtau/hk-bus-crawling/actions/runs/7212537579/job/19715403683#step:8:34 should have pushed https://github.com/rtau/hk-bus-crawling/tree/5ffcaa0d3b358a1d0deb7390d8a548bf99995ea5 and [routeFareList.json](https://github.com/rtau/hk-bus-crawling/blob/5ffcaa0d3b358a1d0deb7390d8a548bf99995ea5/routeFareList.json) is compared to be the same as https://github.com/hkbus/hk-bus-crawling/blob/e5c13acec4bc41dbbbb4542faa7bd8c635bbf3cb/routeFareList.json

**Comment by chunlaw** [comment]
What does "Archive crawling outputs" for?

**Comment by rtau** [comment]
> What does "Archive crawling outputs" for?

It means the pipeline will save those output files generated by the various programs for retrieval for a period of time, like 14 days.

**Pull request merged**
